version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/ssl/certs
      - ./nginx/keys:/etc/ssl/private
    networks:
      - app-network

networks:
  app-network:
    external: true  # 기존 네트워크를 사용
