version: '3.8'

services:
  fitable-app:
    image: fitable:latest
    container_name: fitable-container
    ports:
      - "8081:8081"
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "80:80"
      - "443:443"  # HTTPS 포트 (필요 시 변경 가능)
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/ssl/certs
      - ./nginx/keys:/etc/ssl/private
    depends_on:
      - fitable-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
