version: '3.8'

services:
  fitable-app:
    image: fitable:latest
    container_name: fitable-container
    ports:
      - "8081:8081"
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:?Variable JWT_SECRET_KEY is missing}
      - OPENAI_API_KEY=${OPENAI_API_KEY:?Variable OPENAI_API_KEY is missing}
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro  # 호스트의 절대 경로 사용
      - /etc/nginx/certs:/etc/ssl/certs:ro
      - /etc/nginx/keys:/etc/ssl/private:ro
    depends_on:
      - fitable-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
