version: '3.8'

services:
  fitable-app:
    image: fitable:latest
    container_name: fitable-container
    ports:
      - "8081:8081"
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:?Variable JWT_SECRET_KEY is missing}
      - OPENAI_API_KEY=${OPENAI_API_KEY:?Variable OPENAI_API_KEY is missing}
      - SPRING_REDIS_HOST=redis  # Redis 컨테이너 이름을 호스트로 사용
      - SPRING_REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - fitable-network

  redis:
    image: redis:latest
    container_name: redis-container
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - fitable-network

networks:
  fitable-network:
    driver: bridge
