version: '3.8'

services:
  nginx:
    image: nginx:latest  # Nginx Docker 이미지
    container_name: nginx-container
    ports:
      - "80:80"    # HTTP 포트
      - "443:443"  # HTTPS 포트
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Nginx 설정 파일
      - ./nginx/certs:/etc/ssl/certs             # SSL 인증서
      - ./nginx/keys:/etc/ssl/private            # SSL 키
    networks:
      - app-network  # Nginx와 fitable-container가 연결될 네트워크

networks:
  app-network:
    driver: bridge
